### ISSUE TITLE
enhancement: 'to have items satisfying'

### ISSUE THREAD

**Issue by boneskull** [unexpectedjs/unexpected-set#44]
It'd be handy to be able to express "every item in the set should satisfy _assertion_" (like the core "array" assertion), which I don't think is currently possible.

e.g.:

```js
const set = new Set(['foo', 'bar', 'baz']);
expect(set, 'to have items satisfying', expect.it('to have length', 3));
```

**Comment by papandreou** [comment]
You're in luck! `<Set> to have items satisfying <assertion>` has been implemented since the initial commit :)

It has been undocumented until 18 days ago (#37), though, and it looks like we forgot to update the documentation site after it landed. But here it is: https://unexpected.js.org/unexpected-set/assertions/Set/to-have-items-satisfying/ :hugs:
